// Bundles the editor's ES modules into one file for Filament, which loads an Alpine component as a single file.
// No dependencies: it strips the import and export lines and concatenates the modules in dependency order.
//
//   node scripts/build-editor.mjs           write resources/dist/
//   node scripts/build-editor.mjs --check   fail if resources/dist/ is out of date (used by CI)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'resources/js/editor');
const dist = join(root, 'resources/dist');

// Dependency order: a module comes after the modules it imports.
const MODULES = ['dom.js', 'model.js', 'history.js', 'fields.js', 'odden-mail-editor.js', 'filament-field.js'];

/** Remove `import ... from '...';` (also over several lines) and the `export` keywords, keeping `export default`. */
export function strip(code, file) {
    let out = code.replace(/^import\s[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '');

    out = out.replace(/^export\s+(?!default\b)(async\s+function|function|class|const|let)\b/gm, '$1');

    // `export { a, b }` lists are not used; refuse them rather than silently leave them in.
    if (/^export\s*\{/m.test(out)) {
        throw new Error(`${file}: "export { ... }" lists are not supported by the bundler.`);
    }

    return out;
}

export function bundle() {
    const parts = MODULES.map((file) => {
        let code = strip(readFileSync(join(source, file), 'utf8'), file);

        if (file === 'odden-mail-editor.js') {
            // The stylesheet is a separate asset in the bundled build.
            code = code.replace(/^const STYLESHEET = .*$/m, 'const STYLESHEET = null;');
        }

        return `// ---- ${file}\n${code.trim()}\n`;
    });

    const js = `// Generated by scripts/build-editor.mjs from resources/js/editor. Do not edit.\n\n${parts.join('\n')}`;
    const css = readFileSync(join(source, 'editor.css'), 'utf8');

    return { 'mail-editor.js': js, 'mail-editor.css': css };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const files = bundle();

    if (process.argv.includes('--check')) {
        const stale = Object.entries(files).filter(([name, content]) => !existsSync(join(dist, name)) || readFileSync(join(dist, name), 'utf8') !== content);

        if (stale.length > 0) {
            console.error(`Out of date: ${stale.map(([name]) => name).join(', ')}. Run "node scripts/build-editor.mjs" and commit the result.`);
            process.exit(1);
        }

        console.log('resources/dist is up to date.');
    } else {
        mkdirSync(dist, { recursive: true });

        for (const [name, content] of Object.entries(files)) {
            writeFileSync(join(dist, name), content);
        }

        console.log(`Wrote ${Object.keys(files).join(', ')} to resources/dist.`);
    }
}
